//
//  UMMessage.def.h
//  ummessage
//
//  Created by Andreas Fink on 03.03.2025.
//

// we assume you have include UMMessageFields.h before */
// macros
//type (object,length,tag,dictionary-key,variable-name,accessor-name,database-name,options)

STRING(o ,   37,UMMESSAGE_CODETAG_ARCHIVEID                ,"archive-id"                      ,_archiveId                ,archiveId                ,"archive_id"                  ,"indexed,unique")
INTEGER(o,    2,UMMESSAGE_CODETAG_ARCHIVESTATUS            ,"archive-status"                  ,_archiveStatus            ,archiveStatus            ,"archive_status"              ,"indexed")
STRING(o ,   18,UMMESSAGE_CODETAG_INSTANCENAME             ,"instance"                        ,_instance                 ,instance                 ,"instance"                    ,"indexed")
STRING(o ,   18,UMMESSAGE_CODETAG_MESSAGEID                ,"message-id"                      ,_messageId                ,messageId                ,"message_id"                  ,"indexed")
STRING(o ,   18,UMMESSAGE_CODETAG_USERID                   ,"username"                        ,_userName                 ,userName                 ,"user_name"                   ,"indexed")
STRING(o ,   18,UMMESSAGE_CODETAG_GROUPID                  ,"groupname"                       ,_groupName                ,groupName                ,"group_name"                  ,"indexed")
STRING(o ,   18,UMMESSAGE_CODETAG_DELIVERYMETHOD           ,"delivery-method"                 ,_deliveryMethod           ,deliveryMethod           ,"delivery_method"             ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_SUBMISSIONTYPE           ,"submission-type"                 ,_submissionType           ,submissionType           ,"submission_type"             ,"")
STRING(o ,   32,UMMESSAGE_CODETAG_FROMNUMBER               ,"from-number"                     ,_fromNumber               ,fromNumber               ,"from_number"                 ,"indexed")
STRING(o ,   32,UMMESSAGE_CODETAG_FROMMSC                  ,"from-msc"                        ,_fromMsc                  ,fromMsc                  ,"from_msc"                    ,"indexed")
STRING(o ,   32,UMMESSAGE_CODETAG_FROMIMSI                 ,"from-imsi"                       ,_fromImsi                 ,fromImsi                 ,"from_imsi"                   ,"indexed")
STRING(o ,   40,UMMESSAGE_CODETAG_RECEIVEDFROMIP                   ,"from-ip"                         ,_fromIp                   ,fromIp                   ,"from_ip"                     ,"indexed")
STRING(o ,   32,UMMESSAGE_CODETAG_TONUMBER                 ,"to-number"                       ,_toNumber                 ,toNumber                 ,"to_number"                   ,"indexed")
STRING(o ,   32,UMMESSAGE_CODETAG_TOMSC                    ,"to-msc"                          ,_toMsc                    ,toMsc                    ,"to_msc"                      ,"indexed")
STRING(o ,   32,UMMESSAGE_CODETAG_TOIMSI                   ,"to-imsi"                         ,_toImsi                   ,toImsi                   ,"to_imsi"                     ,"indexed")
STRING(o ,   40,UMMESSAGE_CODETAG_toIp                     ,"to-ip"                           ,_toIp                     ,toIp                     ,"to_ip"                       ,"indexed")
STRING(o ,   32,UMMESSAGE_CODETAG_DELIVERYREPORTMSC        ,"delivery-report-msc"             ,_deliveryReportMsc        ,deliveryReportMsc        ,"delivery_report_msc"         ,"")
STRING(o ,   32,UMMESSAGE_CODETAG_DELIVERYREPORTIMSI       ,"delivery-report-imsi"            ,_deliveryReportImsi       ,deliveryReportImsi       ,"delivery_report_imsi"        ,"")
STRING(o ,   32,UMMESSAGE_CODETAG_SMSC            ,"smsc-srism-gt"                   ,_smsc_srism_gt            ,smsc_srism_gt            ,"smsc_srism_gt"               ,"")
STRING(o ,   32,UMMESSAGE_CODETAG_SMSC2           ,"smsc-srism-map"                  ,_smsc_srism_map           ,smsc_srism_map           ,"smsc_srism_map"              ,"")
STRING(o ,   32,UMMESSAGE_CODETAG_SMSC3              ,"smsc-fsm-gt"                     ,_smsc_fsm_gt              ,smsc_fsm_gt              ,"smsc_fsm_gt"                 ,"")
STRING(o ,   32,UMMESSAGE_CODETAG_SMSC4             ,"smsc-fsm-map"                    ,_smsc_fsm_map             ,smsc_fsm_map             ,"smsc_fsm_map"                ,"")
STRING(o ,   32,UMMESSAGE_CODETAG_HLR                      ,"hlr"                             ,_hlr                      ,hlr                      ,"hlr"                         ,"")
DATE(o   ,   14,UMMESSAGE_CODETAG_CREATED                  ,"created"                         ,_created                  ,created                  ,"created"                     ,"")
DATE(o   ,   14,UMMESSAGE_CODETAG_SCTS                     ,"scts"                            ,_scts                     ,scts                     ,"scts"                        ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_SCTS_TZ                  ,"scts-tz"                         ,_scts_tz                  ,scts_tz                  ,"scts_tz"                     ,"")
INTEGER(o,    2,UMMESSAGE_CODETAG_QPRIORITY                ,"qpriority"                       ,_qpriority                ,qpriority                ,"qpriority"                   ,"")
INTEGER(o,    2,UMMESSAGE_CODETAG_UPRIORITY                ,"upriority"                       ,_upriority                ,upriority                ,"upriority"                   ,"")
INTEGER(o,    2,UMMESSAGE_CODETAG_MESSAGEPRIORITY          ,"message-priority"                ,_messagePriority          ,messagePriority          ,"mpriority"                   ,"")
INTEGER(o,    2,UMMESSAGE_CODETAG_BTYPE              ,"billing-type"                    ,_billingType              ,billingType              ,"billing_type"                ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_MESSAGESTATUS            ,"message-status"                  ,_messageStatus            ,messageStatus            ,"message_status"              ,"indexed")
INTEGER(o,    2,UMMESSAGE_CODETAG_MESSAGEERROR1            ,"message-error1"                  ,_messageError1            ,messageError1            ,"message_error1"              ,"indexed")
INTEGER(o,    2,UMMESSAGE_CODETAG_MESSAGEERROR2            ,"message-error2"                  ,_messageError2            ,messageError2            ,"message_error2"              ,"indexed")
DATE(o   ,   14,UMMESSAGE_CODETAG_MESSAGEDELIVERED         ,"message-delivered"               ,_messageDelivered         ,messageDelivered         ,"delivered"                   ,"indexed")
DATE(o   ,   14,UMMESSAGE_CODETAG_MESSAGEFAILED            ,"failed"                          ,_messageFailed            ,messageFailed            ,"failed"                      ,"indexed")
DATE(o   ,   14,UMMESSAGE_CODETAG_MESSAGEATTEMPTED,"attempted"                       ,_messageAttemptedTimestamp,messageAttemptedTimestamp,"attempted"                   ,"indexed")
DATE(o   ,   14,UMMESSAGE_CODETAG_MESSAGEEXPIRY                 ,"validity"                        ,_validity                 ,validity                 ,"validity"                    ,"indexed")
DATE(o   ,   14,UMMESSAGE_CODETAG_MESSAGENEXTATTEMPT       ,"next-attempt"                    ,_messageNextAttempt       ,messageNextAttemp        ,"next_attempt"                ,"indexed")
INTEGER(o,    2,UMMESSAGE_CODETAG_MESSAGEATTEMPTS          ,"attempts"                        ,_messageAttempts          ,messageAttempts          ,"attempts"                    ,"")
INTEGER(o,    2,UMMESSAGE_CODETAG_MESSAGEMAXATTEMPTS       ,"max-attempts"                    ,_messageMaxAttempts       ,messageMaxAttempts       ,"max_attempts"                ,"")
INTEGER(o,    2,UMMESSAGE_CODETAG_MESSAGEWAITINGSET        ,"message-waiting-set"             ,_messageWaitingSet        ,messageWaitingSet        ,"message_waiting_set"         ,"")
INTEGER(o,    2,UMMESSAGE_CODETAG_DELIVERYREPORTMASK       ,"delivery-report-mask"            ,_deliveryReportMask       ,deliveryReportMask       ,"delivery_report_mask"        ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_DELIVERYREPORTADDRESS    ,"delivery-report-address"         ,_deliveryReportAddress    ,deliveryReportAddress    ,"delivery_report_address"     ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_DELIVERYREPORTSTATUS     ,"delivery-report-status"          ,_deliveryReportStatus     ,deliveryReportStatus     ,"delivery_report_status"      ,"")
INTEGER(o,    2,UMMESSAGE_CODETAG_DELIVERYREPORTERROR1     ,"delivery-report-error1"          ,_deliveryReportError1     ,deliveryReportError1     ,"delivery_report_error1"      ,"")
INTEGER(o,    2,UMMESSAGE_CODETAG_DELIVERYREPORTERROR2     ,"delivery-report-error2"          ,_deliveryReportError2     ,deliveryReportError2     ,"delivery_report_error2"      ,"")
DATE(o   ,   14,UMMESSAGE_CODETAG_DELIVERYREPORTDELIVERED  ,"delivery-report-delivered"       ,_deliveryReportDelivered  ,deliveryReportDelivered  ,"delivery_report_delivered"   ,"")
DATE(o   ,   14,UMMESSAGE_CODETAG_DELIVERYREPORTFAILED     ,"delivery-report-failed"          ,_deliveryReportFailed     ,deliveryReportFailed     ,"delivery_report_failed"      ,"")
DATE(o   ,   14,UMMESSAGE_CODETAG_DELIVERYREPORTATTEMPTED  ,"delivery-report-attempted"       ,_deliveryReportAttempted  ,deliveryReportAttempted  ,"delivery_report_attempted"   ,"")
DATE(o   ,   14,UMMESSAGE_CODETAG_DELIVERYREPORTEXPIRY     ,"delivery-report-expiry"          ,_deliveryReportExpiry     ,deliveryReportExpiry     ,"delivery_report_expiry"      ,"")
DATE(o   ,   14,UMMESSAGE_CODETAG_DELIVERYREPORTNEXTATTEMPT,"delivery-report-next-attempt"    ,_deliveryReportNextAttempt,deliveryReportNextAttempt,"delivery_report_next_attempt","")
INTEGER(o,    2,UMMESSAGE_CODETAG_DELIVERYREPORTATTEMPTS   ,"delivery-report-attempts"        ,_deliveryReportAttempts   ,deliveryReportAttempts   ,"delivery_report_attempts"    ,"")
INTEGER(o,    2,UMMESSAGE_CODETAG_DELIVERYREPORTMAXATTEMPTS,"delivery-report-max-attempts"    ,_deliveryReportMaxAttempts,deliveryReportMaxAttempts,"delivery_report_max_attempts","")
INTEGER(o,    2,UMMESSAGE_CODETAG_DELIVERYREPORTWAITINGSET ,"delivery-report-waiting-set"     ,_deliveryReportWaitingSet ,deliveryReportWaitingSet ,"deliveryReportWaitingSet"    ,"")
INTEGER(o,    2,UMMESSAGE_CODETAG_MSUCOUNTSRISMTX          ,"msu-count-sri-sm-tx"             ,_msuCountSriSMTx          ,msuCountSriSMTx          ,"msu_count_sri_sm_tx"         ,"")
INTEGER(o,    2,UMMESSAGE_CODETAG_MSUCOUNTSRISMRX          ,"msu-count-sri-sm-rx"             ,_msuCountSriSMRx          ,msuCountSriSMRx          ,"msu_count_sri_sm_rx"         ,"")
INTEGER(o,    2,UMMESSAGE_CODETAG_MSUCOUNTSRISMHTX         ,"msu-count-sri-sm-htx"            ,_msuCountSriSMHTx         ,msuCountSriSMHTx         ,"msu_count_sri_sm_htx"        ,"")
INTEGER(o,    2,UMMESSAGE_CODETAG_MSUCOUNTSRISMHRX         ,"msu-count-sri-sm-hrx"            ,_msuCountSriSMHRx         ,msuCountSriSMHRx         ,"msu_count_sri_sm_hrx"        ,"")
INTEGER(o,    2,UMMESSAGE_CODETAG_MSUCOUNTSRISMCRX         ,"msu-count-sri-sm-crx"            ,_msuCountSriSMCRx         ,msuCountSriSMCRx         ,"msu_count_sri_sm_crx"        ,"")
INTEGER(o,    2,UMMESSAGE_CODETAG_MSUCOUNTFSMTX            ,"msu-count-fsm-tx"                ,_msuCountFsmTx            ,msuCountFsmTx            ,"msu_count_fsm_tx"            ,"")
INTEGER(o,    2,UMMESSAGE_CODETAG_MSUCOUNTFSMRX            ,"msu-count-fsm-rx"                ,_msuCountFsmRx            ,msuCountFsmRx            ,"msu_count_fsm_rx"            ,"")
INTEGER(o,    2,UMMESSAGE_CODETAG_MSUCOUNTTCAPHANDSHAKETX  ,"msu-count-tcap-handshake-tx"     ,_msuCountTcapHandshakeTx  ,msuCountTcapHandshakeTx  ,"msu_count_tcap_handshake_tx" ,"")
INTEGER(o,    2,UMMESSAGE_CODETAG_MSUCOUNTTCAPHANDSHAKERX  ,"msu-count-tcap-handshake-rx"     ,_msuCountTcapHandshakeRx  ,msuCountTcapHandshakeRx  ,"msu_count_tcap_handshake_rx" ,"")
INTEGER(o,    1,UMMESSAGE_CODETAG_TESTFLAG                 ,"test-flag"                       ,_testFlag                 ,testFlag                 ,"test_flag"                   ,"")
INTEGER(o,    1,UMMESSAGE_CODETAG_PHONEREF                 ,"phone-ref"                       ,_phoneRef                 ,phoneRef                 ,"phone_ref"                   ,"")
INTEGER(o,    1,UMMESSAGE_CODETAG_UDHINDICATOR          ,"udhi"                            ,_pduUdhIndicator          ,pduUdhIndicator           ,"udhi"                       ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_TOCOUNTRY                ,"to-country"                      ,_toCountry                ,toCountry                ,"to_country"                  ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_TOOPERATORCODE           ,"to-operator-code"                ,_toOperatorCode           ,toOperatorCode           ,"to_operator_code"            ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_TOOPERATORNAME           ,"to-operator-name"                ,_toOperatorName           ,toOperatorName           ,"to_operator_name"            ,"")
INTEGER(o,    1,UMMESSAGE_CODETAG_REPLYPATH       ,"reply-path-indicator"            ,_pduReplyPathIndicator    ,pduReplyPathIndicator    ,"reply_path_indicator"        ,"")
INTEGER(o,    1,UMMESSAGE_CODETAG_PID                   ,"pid"                             ,_pduPid                   ,pduPid                   ,"pid"                         ,"")
INTEGER(o,    1,UMMESSAGE_CODETAG_COMPRESS              ,"compress"                        ,_pduCompress              ,pduCompress              ,"compress"                    ,"")
INTEGER(o,    1,UMMESSAGE_CODETAG_DCS                   ,"dcs"                             ,_pduDcs                   ,pduDcs                   ,"dcs"                         ,"")
INTEGER(o,    1,UMMESSAGE_CODETAG_MWI_PDU                   ,"mwi"                             ,_pduMwi                   ,pduMwi                   ,"mwi"                         ,"")
DATA(o   ,    0,UMMESSAGE_CODETAG_UDH                   ,"udh"                             ,_pduUdh                   ,pduUdh                   ,"udh"                         ,"")
DATA(o   ,    0,UMMESSAGE_CODETAG_CONTENT               ,"content"                         ,_pduContent               ,pduContent               ,"content"                     ,"")
TEXT(o   ,    0,UMMESSAGE_CODETAG_PLAINTEXTCONTENT         ,"plaintext-content"               ,_plaintextContent         ,plaintextContent         ,"plaintext_content"           ,"")
INTEGER(o,    1,UMMESSAGE_CODETAG_esmClass                 ,"esm-class"                       ,_esmClass                 ,esmClass                 ,"esm_class"                   ,"")
INTEGER(o,    1,UMMESSAGE_CODETAG_MESSAGECLASS             ,"message-class"                   ,_messageClass             ,messageClass             ,"message_class"               ,"")
STRING(o,    18,UMMESSAGE_CODETAG_CODING                ,"coding"                          ,_pduCoding                ,pduCoding                ,"coding"                      ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_OPC                ,"opc-srism"                       ,_opc_srism                ,opc_srism                ,"opc_srism"                   ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_DPC                ,"dpc-srism"                       ,_dpc_srism                ,dpc_srism                ,"dpc_srism"                   ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_OPC2                  ,"opc-fsm"                         ,_opc_fsm                  ,opc_fsm                  ,"opc_fsm"                     ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_DPC2                  ,"dpc-fsm"                         ,_dpc_fsm                  ,dpc_fsm                  ,"dpc_fsm"                     ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_TCAPTYPE                 ,"tcap-type"                       ,_tcapType                 ,tcapType                 ,"tcap_type"                   ,"")
TEXT(o,       0,UMMESSAGE_CODETAG_EXTENSIONDATA            ,"extension-data"                  ,_extensionData            ,extensionData            ,"extension_data"              ,"")
INTEGER(o,    1,UMMESSAGE_CODETAG_PURGEFLAG                ,"purge-flag"                      ,_purgeFlag                ,purgeFlag                ,"purge_flag"                  ,"indexed")
STRING(o ,   18,UMMESSAGE_CODETAG_ALERTINGADDRESS          ,"alerting-address"                ,_alertingAddress          ,alertingAddress          ,"alerting_address"            ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_FROMCOUNTRY              ,"from-country"                    ,_fromCountry              ,fromCountry              ,"from_country"                ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_FROMOPERATORCODE         ,"from-operator-code"              ,_fromOperatorCode         ,fromOperatorCode         ,"from_cperator_code"          ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_FROMOPERATORNAME         ,"from-operator-name"              ,_fromOperatorName         ,fromOperatorName         ,"from_operator_name"          ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_ROUTEID                  ,"route-id"                        ,_routeId                  ,routeId                  ,"route_id"                    ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_SUBROUTEID               ,"subroute-id"                     ,_subrouteId               ,subrouteId               ,"subroute_id"                 ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_ROUTEDONPREFIX           ,"routed-on-prefix"                ,_routedOnPrefix           ,routedOnPrefix           ,"routed_on_prefix"            ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_AUTOROUTED               ,"auto-routed"                     ,_autoRouted               ,autoRouted               ,"auto_routed"                 ,"")
INTEGER(o,    2,UMMESSAGE_CODETAG_USERFLAGS                ,"user-flags"                      ,_userFlags                ,userFlags                ,"user_flags"                  ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_INTERWORKINGTAPCODE      ,"interworking-tap-code"           ,_interworkingTapCode      ,interworkingTapCode      ,"interworking_tap_code"       ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_COSTTABLE                ,"cost-table"                      ,_costTable                ,costTable                ,"cost_table"                  ,"")
DOUBLE(o ,    0,UMMESSAGE_CODETAG_MSUCOSTTX                ,"msu-cost-tx"                     ,_msuCostTx                ,msuCostTx                ,"msu_cost_tx"                 ,"")
DOUBLE(o ,    0,UMMESSAGE_CODETAG_MSUCOSTRX                ,"msu-cost-rx"                     ,_msuCostRx                ,msuCostRx                ,"msu_cost_rx"                 ,"")
DOUBLE(o ,    0,UMMESSAGE_CODETAG_SMSCOST                  ,"sms-cost"                        ,_smsCost                  ,smsCost                  ,"sms_cost"                    ,"")
DOUBLE(o ,    0,UMMESSAGE_CODETAG_INTERWORKINGCOST         ,"interworking-cost"               ,_interworkingCost         ,interworkingCost         ,"interworking_cost"           ,"")
DOUBLE(o ,    0,UMMESSAGE_CODETAG_TOTALCOST                ,"total-cost"                      ,_totalCost                ,totalCost                ,"total_coost"                 ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_CHARGETABLE1             ,"charge-table1"                   ,_chargeTable1             ,chargeTable1             ,"charge_table1"               ,"")
DOUBLE(o ,    0,UMMESSAGE_CODETAG_CHARGEPRICE1             ,"charge-price1"                   ,_chargePrice1             ,chargePrice1             ,"charge_price1"               ,"")
DOUBLE(o ,    0,UMMESSAGE_CODETAG_PROFIT1                  ,"profit1"                         ,_profit1                  ,profit1                  ,"profit1"                     ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_CHARGETABLE2             ,"cahrge-table2"                   ,_chargeTable2             ,chargeTable2             ,"charge_table2"               ,"")
DOUBLE(o ,    0,UMMESSAGE_CODETAG_CHARGEPRICE2             ,"cahrge-price2"                   ,_chargePrice2             ,chargePrice2             ,"charge_price2"               ,"")
DOUBLE(o ,    0,UMMESSAGE_CODETAG_PROFIT2                  ,"profit2"                         ,_profit2                  ,profit2                  ,"profit2"                     ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_DESTINATIONQUOTATABLE    ,"destination-quota-table"         ,_destinationQuotaTable    ,destinationQuotaTable    ,"destination_quota_table"     ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_RETRYPATTERNTABLE        ,"retry-pattern-table"             ,_retryPatternTable        ,retryPatternTable        ,"retry_pattern"               ,"")
INTEGER(o,    1,UMMESSAGE_CODETAG_TT_SRI                   ,"tt-sri"                          ,_tt_sri                   ,tt_sri                   ,"tt_sri"                      ,"")
INTEGER(o,    1,UMMESSAGE_CODETAG_TT_FSM                   ,"tt-fsm"                          ,_tt_fsm                   ,tt_fsm                   ,"tt_fsm"                      ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_DLR_TEXT               ,"dlr-text"                        ,_dlr_text                 ,dlr_text                 ,"dlr_text"                    ,"")
TEXT(o ,      0,UMMESSAGE_CODETAG_COMMENT_TEXT                  ,"comment"                         ,_comment                  ,comment                  ,"comment"                     ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_HLR_OVERRIDE             ,"hlr-override"                    ,_hlr_override             ,hlr_override             ,"hlr_override"                ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_VAS_ESME                 ,"vas-esme"                        ,_vas_esme                 ,vas_esme                 ,"vas_esme"                    ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_VAS_IP                   ,"vas-ip"                          ,_vas_ip                   ,vas_ip                   ,"vas_ip"                      ,"")
DATE(o   ,   14,UMMESSAGE_CODETAG_deferred                 ,"deferred"                        ,_deferred                 ,deferred                 ,"deferred"                    ,"")
INTEGER(o,    1,UMMESSAGE_CODETAG_EXPORTED                 ,"exported"                        ,_exported                 ,exported                 ,"exported"                    ,"")

TEXT(o ,      0,UMMESSAGE_CODETAG_options                  ,"options"                         ,_options                  ,options                  ,"options"                     ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_inboundMethod            ,"inbound-method"                  ,_inboundMethod            ,inboundMethod            ,"inbound_method"              ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_inboundType              ,"inbound-type"                    ,_inboundType              ,inboundType              ,"inbound_type"                ,"")
DATA(o   ,    0,UMMESSAGE_CODETAG_userMessageReference     ,"user-message-reference"          ,_userMessageReference     ,userMessageReference     ,"user_message_reference"      ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_userReference            ,"user-reference"                  ,_userReference            ,userReference            ,"user_reference"              ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_providerReference        ,"provider-reference"              ,_providerReference        ,providerReference        ,"provider_reference"          ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_routerReference          ,"router-reference"                ,_routerReference          ,routerReference          ,"router_reference"            ,"")
DATE(o   ,   14,UMMESSAGE_CODETAG_submitTimestamp          ,"submit-timestamp"                ,_submitTimestamp          ,submitTimestamp          ,"submit_ts"                   ,"")
DATE(o   ,   14,UMMESSAGE_CODETAG_submitAckTimestamp       ,"submit-ack-timestamp"            ,_submitAckTimestamp       ,submitAckTimestamp       ,"submit_ack_ts"               ,"")
DATE(o   ,   14,UMMESSAGE_CODETAG_submitErrorTimestamp     ,"submit-err-timestamp"            ,_submitErrorTimestamp     ,submitErrorTimestamp     ,"submit_error_ts"             ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_submitString             ,"submit-string"                   ,_submitString             ,submitString             ,"submit_string"               ,"")
INTEGER(o,    1,UMMESSAGE_CODETAG_submitErrorCode          ,"submit-error-code"               ,_submitErrorCode          ,submitErrorCode          ,"submit_error_code"           ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_method                   ,"method"                          ,_method                   ,method                   ,"method"                      ,"")
INTEGER(o,    1,UMMESSAGE_CODETAG_networkErrorCode         ,"network-error-code"              ,_networkErrorCode         ,networkErrorCode         ,"network_error_code"          ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_deliveryReportNumber     ,"delivery-report-number"          ,_deliveryReportNumber     ,deliveryReportNumber     ,"delivery_report_number"      ,"")
INTEGER(o ,   1,UMMESSAGE_CODETAG_replaceIfPresentFlag     ,"replace-if-present"              ,_replaceIfPresentFlag     ,replaceIfPresentFlag     ,"replace_if_present"          ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_type                     ,"type"                            ,_type                     ,type                     ,"type"                        ,"")
STRING(o ,   18,UMMESSAGE_CODETAG_linkedMessageId          ,"linked-message-id"               ,_linkedMessageId          ,linkedMessageId          ,"linked_message_id"           ,"indexed")
INTEGER(o,    1,UMMESSAGE_CODETAG_multipartRef             ,"multipart-ref"                   ,_multipartRef             ,multipartRef             ,"multipart_ref"               ,"")
INTEGER(o,    1,UMMESSAGE_CODETAG_currentPart              ,"current-part"                    ,_currentPart              ,currentPart              ,"current_part"                ,"")
INTEGER(o,    1,UMMESSAGE_CODETAG_maxParts                 ,"max-parts"                       ,_maxParts                 ,maxParts                 ,"max_parts"                   ,"")
TEXT(o ,      0,UMMESSAGE_CODETAG_inboundMessageIds        ,"inbound-message-ids"             ,_inboundMessageIds        ,inboundMessageIds        ,"inbound_message_ids"         ,"")
TEXT(o ,      0,UMMESSAGE_CODETAG_outboundMessageIds       ,"outbound-message-ids"            ,_outboundMessageIds      ,outboundMessageIds        ,"outbound_message_ids"        ,"")

