//
//  UMMessageFields.h
//  ummessage
//
//  Created by Andreas Fink on 03.03.2025
//

typedef enum    UMMessageFields
{
    /* basic fields */
    UMMESSAGE_CODETAG_ARCHIVEID                 = 1,
    UMMESSAGE_CODETAG_ARCHIVESTATUS             = 2,
    UMMESSAGE_CODETAG_INSTANCENAME              = 3,
    UMMESSAGE_CODETAG_MESSAGEID                 = 4,
    UMMESSAGE_CODETAG_USERID                    = 5,
    UMMESSAGE_CODETAG_GROUPID                   = 6,
    UMMESSAGE_CODETAG_DELIVERYMETHOD            = 7,
    UMMESSAGE_CODETAG_SUBMISSIONMETHOD          = 8,
    UMMESSAGE_CODETAG_SUBMISSIONTYPE            = 9,
    UMMESSAGE_CODETAG_PURGEFLAG                 = 10,
    UMMESSAGE_CODETAG_USERFLAGS                 = 11,
    UMMESSAGE_CODETAG_RETRYPATTERNTABLE         = 12,
    UMMESSAGE_CODETAG_TYPE                      = 13,
    UMMESSAGE_CODETAG_NETWORK_ERROR_CODE        = 14,
    UMMESSAGE_CODETAG_VAS_ESME                  = 15,
    UMMESSAGE_CODETAG_VAS_IP                    = 16,
    UMMESSAGE_CODETAG_EXPORTED                  = 17,
    UMMESSAGE_CODETAG_OPTIONS                   = 18,

    /* source related fields */
    UMMESSAGE_CODETAG_FROMNUMBER                = 20,
    UMMESSAGE_CODETAG_FROMMSC                   = 21,
    UMMESSAGE_CODETAG_FROMIMSI                  = 22,
    UMMESSAGE_CODETAG_FROMIP                    = 23,
    UMMESSAGE_CODETAG_FROMCOUNTRY               = 24,
    UMMESSAGE_CODETAG_FROMOPERATORCODE          = 25,
    UMMESSAGE_CODETAG_FROMOPERATORNAME          = 26,

    /* destination related fields */
    UMMESSAGE_CODETAG_TONUMBER                  = 30,
    UMMESSAGE_CODETAG_TOMSC                     = 31,
    UMMESSAGE_CODETAG_TOIMSI                    = 32,
    UMMESSAGE_CODETAG_TOIP                      = 33,
    UMMESSAGE_CODETAG_TOCOUNTRY                 = 34,
    UMMESSAGE_CODETAG_TOOPERATORCODE            = 35,
    UMMESSAGE_CODETAG_TOOPERATORNAME            = 36,
    UMMESSAGE_CODETAG_MCC                       = 37,
    UMMESSAGE_CODETAG_MNC                       = 38,

    /* report related fields */
    UMMESSAGE_CODETAG_DELIVERYREPORTADDRESS     = 40,
    UMMESSAGE_CODETAG_DELIVERYREPORTMSC         = 41,
    UMMESSAGE_CODETAG_DELIVERYREPORTIMSI        = 42,
    UMMESSAGE_CODETAG_DELIVERYREPORTIP          = 43,

    UMMESSAGE_CODETAG_DELIVERYREPORTMASK        = 50,
    UMMESSAGE_CODETAG_ALERTINGADDRESS           = 51,
    UMMESSAGE_CODETAG_DLR_TEXT                  = 52,
    UMMESSAGE_CODETAG_REPLACE_IF_PRESENT        = 53,

    /* MTP3 */
    UMMESSAGE_CODETAG_OPC_SRISM                 = 54,
    UMMESSAGE_CODETAG_DPC_SRISM                 = 55,
    UMMESSAGE_CODETAG_OPC_FSM                   = 56,
    UMMESSAGE_CODETAG_DPC_FSM                   = 57,

    /* sccp related fields */
    UMMESSAGE_CODETAG_SMSC_SRISM_GT             = 60,
    UMMESSAGE_CODETAG_SMSC_FSM_GT               = 61,
    UMMESSAGE_CODETAG_SMSC_SRISM_MAP            = 62,
    UMMESSAGE_CODETAG_SMSC_FSM_MAP              = 63,
    UMMESSAGE_CODETAG_HLR                       = 64,
    UMMESSAGE_CODETAG_TT_SRISM                  = 65,
    UMMESSAGE_CODETAG_TT_FSM                    = 66,
    UMMESSAGE_CODETAG_HLR_OVERRIDE              = 67,

    /* timestamps and message delivery */
    UMMESSAGE_CODETAG_CREATED                   = 70,
    UMMESSAGE_CODETAG_SCTS                      = 71,
    UMMESSAGE_CODETAG_SCTS_TZ                   = 72,
    UMMESSAGE_CODETAG_QPRIORITY                 = 73,
    UMMESSAGE_CODETAG_UPRIORITY                 = 74,
    UMMESSAGE_CODETAG_MESSAGEPRIORITY           = 75,
    UMMESSAGE_CODETAG_BTYPE                     = 76,
    UMMESSAGE_CODETAG_TESTFLAG                  = 77,
    UMMESSAGE_CODETAG_DEFERRED                  = 78,
    
    /* message status related fields */
    UMMESSAGE_CODETAG_MESSAGESTATUS             = 80,
    UMMESSAGE_CODETAG_MESSAGEERROR              = 81,
    UMMESSAGE_CODETAG_MESSAGEDELIVERED          = 82,
    UMMESSAGE_CODETAG_MESSAGEFAILED             = 83,
    UMMESSAGE_CODETAG_MESSAGEATTEMPTED          = 84,
    UMMESSAGE_CODETAG_MESSAGEEXPIRY             = 85,
    UMMESSAGE_CODETAG_MESSAGENEXTATTEMPT        = 86,
    UMMESSAGE_CODETAG_MESSAGEATTEMPTS           = 87,
    UMMESSAGE_CODETAG_MESSAGEMAXATTEMPTS        = 88,
    UMMESSAGE_CODETAG_MESSAGEWAITINGSET         = 89,

    /* report status related fields */
    UMMESSAGE_CODETAG_DELIVERYREPORTSTATUS      = 90,
    UMMESSAGE_CODETAG_DELIVERYREPORTERROR       = 91,
    UMMESSAGE_CODETAG_DELIVERYREPORTDELIVERED   = 92,
    UMMESSAGE_CODETAG_DELIVERYREPORTFAILED      = 93,
    UMMESSAGE_CODETAG_DELIVERYREPORTATTEMPTED   = 94,
    UMMESSAGE_CODETAG_DELIVERYREPORTEXPIRY      = 95,
    UMMESSAGE_CODETAG_DELIVERYREPORTNEXTATTEMPT = 96,
    UMMESSAGE_CODETAG_DELIVERYREPORTATTEMPTS    = 97,
    UMMESSAGE_CODETAG_DELIVERYREPORTMAXATTEMPTS = 98,
    UMMESSAGE_CODETAG_DELIVERYREPORTWAITINGSET  = 99,
    
    /* MSU statistics */
    UMMESSAGE_CODETAG_MSUCOUNTSRISMTX           = 100,
    UMMESSAGE_CODETAG_MSUCOUNTSRISMRX           = 101,
    UMMESSAGE_CODETAG_MSUCOUNTSRISMHTX          = 102,
    UMMESSAGE_CODETAG_MSUCOUNTSRISMHRX          = 103,
    UMMESSAGE_CODETAG_MSUCOUNTSRISMCRX          = 104,
    UMMESSAGE_CODETAG_MSUCOUNTFSMTX             = 105,
    UMMESSAGE_CODETAG_MSUCOUNTFSMRX             = 106,
    UMMESSAGE_CODETAG_MSUCOUNTTCAPHANDSHAKETX   = 107,
    UMMESSAGE_CODETAG_MSUCOUNTTCAPHANDSHAKERX   = 108,
    
    /* pdu payload fields */
    UMMESSAGE_CODETAG_PHONEREF                  = 110,
    UMMESSAGE_CODETAG_UDHINDICATOR              = 111,
    UMMESSAGE_CODETAG_REPLYPATH                 = 112,
    UMMESSAGE_CODETAG_PID                       = 113,
    UMMESSAGE_CODETAG_COMPRESS                  = 114,
    UMMESSAGE_CODETAG_DCS                       = 115,
    UMMESSAGE_CODETAG_MWI_PDU                   = 116,
    UMMESSAGE_CODETAG_UDH                       = 117,
    UMMESSAGE_CODETAG_CONTENT                   = 118,
    UMMESSAGE_CODETAG_PLAINTEXTCONTENT          = 119,
    UMMESSAGE_CODETAG_MESSAGECLASS              = 120,
    UMMESSAGE_CODETAG_CODING                    = 121,
    UMMESSAGE_CODETAG_EXTENSIONDATA             = 122,
    UMMESSAGE_CODETAG_ESMCLASS                  = 123,

    /* costing table fields */
    UMMESSAGE_CODETAG_COSTTABLE                 = 130,
    UMMESSAGE_CODETAG_MSUCOSTTX                 = 131,
    UMMESSAGE_CODETAG_MSUCOSTRX                 = 132,
    UMMESSAGE_CODETAG_SMSCOST                   = 133,
    UMMESSAGE_CODETAG_INTERWORKINGCOST          = 134,
    UMMESSAGE_CODETAG_INTERWORKINGTAPCODE       = 135,
    UMMESSAGE_CODETAG_TOTALCOST                 = 136,
    UMMESSAGE_CODETAG_CHARGETABLE1              = 137,
    UMMESSAGE_CODETAG_CHARGEPRICE1              = 138,
    UMMESSAGE_CODETAG_CURRENCY1                 = 139,
    UMMESSAGE_CODETAG_PROFIT1                   = 140,
    UMMESSAGE_CODETAG_CHARGETABLE2              = 141,
    UMMESSAGE_CODETAG_CHARGEPRICE2              = 142,
    UMMESSAGE_CODETAG_CURRENCY2                    = 143,
    UMMESSAGE_CODETAG_PROFIT2                   = 144,
    UMMESSAGE_CODETAG_DESTINATIONQUOTATABLE     = 145,

    /* various */
    UMMESSAGE_CODETAG_COMMENT_TEXT              = 150,
    UMMESSAGE_CODETAG_USER_MESSAGE_REFERENCE    = 151,
    UMMESSAGE_CODETAG_USER_REFERENCE            = 152,
    UMMESSAGE_CODETAG_PROVIDER_REFERENCE        = 153,
    UMMESSAGE_CODETAG_ROUTER_REFERENCE          = 154,
    UMMESSAGE_CODETAG_MULTIPART_REF             = 155,
    UMMESSAGE_CODETAG_CURRENT_PART              = 156,
    UMMESSAGE_CODETAG_MAX_PARTS                 = 157,
    UMMESSAGE_CODETAG_LINKED_MESSAGE_ID         = 158,
    UMMESSAGE_CODETAG_INBOUND_MESSAGE_IDS       = 159,
    UMMESSAGE_CODETAG_OUTBOUND_MESSAGE_IDS      = 160,

    /* smpp specific fields */
    UMMESSAGE_CODETAG_SUBMIT_TIMESTAMP          = 170,
    UMMESSAGE_CODETAG_SUBMIT_ACK_TIMESTAMP      = 171,
    UMMESSAGE_CODETAG_SUBMIT_ERROR_TIMESTAMP    = 172,
    UMMESSAGE_CODETAG_SUBMIT_STRING             = 173,
    UMMESSAGE_CODETAG_SUBMIT_ERROR_CODE         = 174,
    
    /* routing fields */
    UMMESSAGE_CODETAG_AUTOROUTED                = 180,
    UMMESSAGE_CODETAG_ROUTEID                   = 181,
    UMMESSAGE_CODETAG_SUBROUTEID                = 182,
    UMMESSAGE_CODETAG_ROUTEDONPREFIX            = 183,
} UMMessageFields;

