//
//  UMMessage.def.h
//  ummessage
//
//  Created by Andreas Fink on 03.03.2025.
//

// we assume you have include UMMessageFields.h before */
// macros
//type (object,length,tag,dictionary-key,variable-name,accessor-name,database-name,options)

STRING(o ,   37,UMMESSAGE_CODETAG_ARCHIVEID                 ,"archive-id"                      ,_archiveId                ,archiveId                ,"archive_id"                  ,"indexed,unique,mandatory")
INTEGER(o,    2,UMMESSAGE_CODETAG_ARCHIVESTATUS             ,"archive-status"                  ,_archiveStatus            ,archiveStatus            ,"archive_status"              ,"indexed,mandatory")
STRING(o ,   18,UMMESSAGE_CODETAG_INSTANCENAME              ,"instance"                        ,_instance                 ,instance                 ,"instance"                    ,"indexed,mandatory")
STRING(o ,   18,UMMESSAGE_CODETAG_MESSAGEID                 ,"message-id"                      ,_messageId                ,messageId                ,"message_id"                  ,"indexed,mandatory")
STRING(o ,   18,UMMESSAGE_CODETAG_USERID                    ,"username"                        ,_userName                 ,userName                 ,"user_name"                   ,"indexed,optional")
STRING(o ,   18,UMMESSAGE_CODETAG_GROUPID                   ,"groupname"                       ,_groupName                ,groupName                ,"group_name"                  ,"indexed,optional")
STRING(o ,   18,UMMESSAGE_CODETAG_DELIVERYMETHOD            ,"delivery-method"                 ,_deliveryMethod           ,deliveryMethod           ,"delivery_method"             ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_SUBMISSIONTYPE            ,"submission-type"                 ,_submissionType           ,submissionType           ,"submission_type"             ,"optional")
STRING(o ,   32,UMMESSAGE_CODETAG_FROMNUMBER                ,"from-number"                     ,_fromNumber               ,fromNumber               ,"from_number"                 ,"indexed,optional")
STRING(o ,   32,UMMESSAGE_CODETAG_FROMMSC                   ,"from-msc"                        ,_fromMsc                  ,fromMsc                  ,"from_msc"                    ,"indexed,optional")
STRING(o ,   32,UMMESSAGE_CODETAG_FROMIMSI                  ,"from-imsi"                       ,_fromImsi                 ,fromImsi                 ,"from_imsi"                   ,"indexed,optional")
STRING(o ,   40,UMMESSAGE_CODETAG_FROMIP                    ,"from-ip"                         ,_fromIp                   ,fromIp                   ,"from_ip"                     ,"indexed,optional")
STRING(o ,   32,UMMESSAGE_CODETAG_TONUMBER                  ,"to-number"                       ,_toNumber                 ,toNumber                 ,"to_number"                   ,"indexed,optional")
STRING(o ,   32,UMMESSAGE_CODETAG_TOMSC                     ,"to-msc"                          ,_toMsc                    ,toMsc                    ,"to_msc"                      ,"indexed,optional")
STRING(o ,   32,UMMESSAGE_CODETAG_TOIMSI                    ,"to-imsi"                         ,_toImsi                   ,toImsi                   ,"to_imsi"                     ,"indexed,optional")
STRING(o ,   40,UMMESSAGE_CODETAG_TOIP                      ,"to-ip"                           ,_toIp                     ,toIp                     ,"to_ip"                       ,"indexed,optional")
STRING(o ,   32,UMMESSAGE_CODETAG_DELIVERYREPORTMSC         ,"delivery-report-msc"             ,_deliveryReportMsc        ,deliveryReportMsc        ,"delivery_report_msc"         ,"optional")
STRING(o ,   32,UMMESSAGE_CODETAG_DELIVERYREPORTIMSI        ,"delivery-report-imsi"            ,_deliveryReportImsi       ,deliveryReportImsi       ,"delivery_report_imsi"        ,"optional")
STRING(o ,   32,UMMESSAGE_CODETAG_SMSC_SRISM_GT             ,"smsc-srism-gt"                   ,_smsc_srism_gt            ,smsc_srism_gt            ,"smsc_srism_gt"               ,"optional")
STRING(o ,   32,UMMESSAGE_CODETAG_SMSC_SRISM_MAP            ,"smsc-srism-map"                  ,_smsc_srism_map           ,smsc_srism_map           ,"smsc_srism_map"              ,"optional")
STRING(o ,   32,UMMESSAGE_CODETAG_SMSC_FSM_GT               ,"smsc-fsm-gt"                     ,_smsc_fsm_gt              ,smsc_fsm_gt              ,"smsc_fsm_gt"                 ,"optional")
STRING(o ,   32,UMMESSAGE_CODETAG_SMSC_FSM_MAP              ,"smsc-fsm-map"                    ,_smsc_fsm_map             ,smsc_fsm_map             ,"smsc_fsm_map"                ,"optional")
STRING(o ,   32,UMMESSAGE_CODETAG_HLR                       ,"hlr"                             ,_hlr                      ,hlr                      ,"hlr"                         ,"optional")
DATE(o   ,   14,UMMESSAGE_CODETAG_CREATED                   ,"created"                         ,_created                  ,created                  ,"created"                     ,"optional")
DATE(o   ,   14,UMMESSAGE_CODETAG_SCTS                      ,"scts"                            ,_scts                     ,scts                     ,"scts"                        ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_SCTS_TZ                   ,"scts-tz"                         ,_scts_tz                  ,scts_tz                  ,"scts_tz"                     ,"optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_QPRIORITY                 ,"qpriority"                       ,_qpriority                ,qpriority                ,"qpriority"                   ,"optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_UPRIORITY                 ,"upriority"                       ,_upriority                ,upriority                ,"upriority"                   ,"optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_MESSAGEPRIORITY           ,"message-priority"                ,_messagePriority          ,messagePriority          ,"mpriority"                   ,"optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_BTYPE                     ,"billing-type"                    ,_billingType              ,billingType              ,"billing_type"                ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_MESSAGESTATUS             ,"message-status"                  ,_messageStatus            ,messageStatus            ,"message_status"              ,"indexed,optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_MESSAGEERROR1             ,"message-error1"                  ,_messageError1            ,messageError1            ,"message_error1"              ,"indexed,optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_MESSAGEERROR2             ,"message-error2"                  ,_messageError2            ,messageError2            ,"message_error2"              ,"indexed,optional")
DATE(o   ,   14,UMMESSAGE_CODETAG_MESSAGEDELIVERED          ,"message-delivered"               ,_messageDelivered         ,messageDelivered         ,"delivered"                   ,"indexed,optional")
DATE(o   ,   14,UMMESSAGE_CODETAG_MESSAGEFAILED             ,"failed"                          ,_messageFailed            ,messageFailed            ,"failed"                      ,"indexed,optional")
DATE(o   ,   14,UMMESSAGE_CODETAG_MESSAGEATTEMPTED          ,"attempted"                       ,_messageAttemptedTimestamp,messageAttemptedTimestamp,"attempted"                   ,"indexed,optional")
DATE(o   ,   14,UMMESSAGE_CODETAG_MESSAGEEXPIRY             ,"validity"                        ,_validity                 ,validity                 ,"validity"                    ,"indexed,optional")
DATE(o   ,   14,UMMESSAGE_CODETAG_MESSAGENEXTATTEMPT        ,"next-attempt"                    ,_messageNextAttempt       ,messageNextAttemp        ,"next_attempt"                ,"indexed,optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_MESSAGEATTEMPTS           ,"attempts"                        ,_messageAttempts          ,messageAttempts          ,"attempts"                    ,"optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_MESSAGEMAXATTEMPTS        ,"max-attempts"                    ,_messageMaxAttempts       ,messageMaxAttempts       ,"max_attempts"                ,"optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_MESSAGEWAITINGSET         ,"message-waiting-set"             ,_messageWaitingSet        ,messageWaitingSet        ,"message_waiting_set"         ,"optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_DELIVERYREPORTMASK        ,"delivery-report-mask"            ,_deliveryReportMask       ,deliveryReportMask       ,"delivery_report_mask"        ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_DELIVERYREPORTADDRESS     ,"delivery-report-address"         ,_deliveryReportAddress    ,deliveryReportAddress    ,"delivery_report_address"     ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_DELIVERYREPORTSTATUS      ,"delivery-report-status"          ,_deliveryReportStatus     ,deliveryReportStatus     ,"delivery_report_status"      ,"optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_DELIVERYREPORTERROR1      ,"delivery-report-error1"          ,_deliveryReportError1     ,deliveryReportError1     ,"delivery_report_error1"      ,"optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_DELIVERYREPORTERROR2      ,"delivery-report-error2"          ,_deliveryReportError2     ,deliveryReportError2     ,"delivery_report_error2"      ,"optional")
DATE(o   ,   14,UMMESSAGE_CODETAG_DELIVERYREPORTDELIVERED   ,"delivery-report-delivered"       ,_deliveryReportDelivered  ,deliveryReportDelivered  ,"delivery_report_delivered"   ,"optional")
DATE(o   ,   14,UMMESSAGE_CODETAG_DELIVERYREPORTFAILED      ,"delivery-report-failed"          ,_deliveryReportFailed     ,deliveryReportFailed     ,"delivery_report_failed"      ,"optional")
DATE(o   ,   14,UMMESSAGE_CODETAG_DELIVERYREPORTATTEMPTED   ,"delivery-report-attempted"       ,_deliveryReportAttempted  ,deliveryReportAttempted  ,"delivery_report_attempted"   ,"optional")
DATE(o   ,   14,UMMESSAGE_CODETAG_DELIVERYREPORTEXPIRY      ,"delivery-report-expiry"          ,_deliveryReportExpiry     ,deliveryReportExpiry     ,"delivery_report_expiry"      ,"optional")
DATE(o   ,   14,UMMESSAGE_CODETAG_DELIVERYREPORTNEXTATTEMPT ,"delivery-report-next-attempt"    ,_deliveryReportNextAttempt,deliveryReportNextAttempt,"delivery_report_next_attempt","optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_DELIVERYREPORTATTEMPTS    ,"delivery-report-attempts"        ,_deliveryReportAttempts   ,deliveryReportAttempts   ,"delivery_report_attempts"    ,"optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_DELIVERYREPORTMAXATTEMPTS ,"delivery-report-max-attempts"    ,_deliveryReportMaxAttempts,deliveryReportMaxAttempts,"delivery_report_max_attempts","optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_DELIVERYREPORTWAITINGSET  ,"delivery-report-waiting-set"     ,_deliveryReportWaitingSet ,deliveryReportWaitingSet ,"deliveryReportWaitingSet"    ,"optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_MSUCOUNTSRISMTX           ,"msu-count-sri-sm-tx"             ,_msuCountSriSMTx          ,msuCountSriSMTx          ,"msu_count_sri_sm_tx"         ,"optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_MSUCOUNTSRISMRX           ,"msu-count-sri-sm-rx"             ,_msuCountSriSMRx          ,msuCountSriSMRx          ,"msu_count_sri_sm_rx"         ,"optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_MSUCOUNTSRISMHTX          ,"msu-count-sri-sm-htx"            ,_msuCountSriSMHTx         ,msuCountSriSMHTx         ,"msu_count_sri_sm_htx"        ,"optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_MSUCOUNTSRISMHRX          ,"msu-count-sri-sm-hrx"            ,_msuCountSriSMHRx         ,msuCountSriSMHRx         ,"msu_count_sri_sm_hrx"        ,"optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_MSUCOUNTSRISMCRX          ,"msu-count-sri-sm-crx"            ,_msuCountSriSMCRx         ,msuCountSriSMCRx         ,"msu_count_sri_sm_crx"        ,"optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_MSUCOUNTFSMTX             ,"msu-count-fsm-tx"                ,_msuCountFsmTx            ,msuCountFsmTx            ,"msu_count_fsm_tx"            ,"optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_MSUCOUNTFSMRX             ,"msu-count-fsm-rx"                ,_msuCountFsmRx            ,msuCountFsmRx            ,"msu_count_fsm_rx"            ,"optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_MSUCOUNTTCAPHANDSHAKETX   ,"msu-count-tcap-handshake-tx"     ,_msuCountTcapHandshakeTx  ,msuCountTcapHandshakeTx  ,"msu_count_tcap_handshake_tx" ,"optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_MSUCOUNTTCAPHANDSHAKERX   ,"msu-count-tcap-handshake-rx"     ,_msuCountTcapHandshakeRx  ,msuCountTcapHandshakeRx  ,"msu_count_tcap_handshake_rx" ,"optional")
INTEGER(o,    1,UMMESSAGE_CODETAG_TESTFLAG                  ,"test-flag"                       ,_testFlag                 ,testFlag                 ,"test_flag"                   ,"optional")
INTEGER(o,    1,UMMESSAGE_CODETAG_PHONEREF                  ,"phone-ref"                       ,_phoneRef                 ,phoneRef                 ,"phone_ref"                   ,"optional")
INTEGER(o,    1,UMMESSAGE_CODETAG_UDHINDICATOR              ,"udhi"                            ,_pduUdhIndicator          ,pduUdhIndicator           ,"udhi"                       ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_TOCOUNTRY                 ,"to-country"                      ,_toCountry                ,toCountry                ,"to_country"                  ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_TOOPERATORCODE            ,"to-operator-code"                ,_toOperatorCode           ,toOperatorCode           ,"to_operator_code"            ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_TOOPERATORNAME            ,"to-operator-name"                ,_toOperatorName           ,toOperatorName           ,"to_operator_name"            ,"optional")
INTEGER(o,    1,UMMESSAGE_CODETAG_REPLYPATH                 ,"reply-path-indicator"            ,_pduReplyPathIndicator    ,pduReplyPathIndicator    ,"reply_path_indicator"        ,"optional")
INTEGER(o,    1,UMMESSAGE_CODETAG_PID                       ,"pid"                             ,_pduPid                   ,pduPid                   ,"pid"                         ,"optional")
INTEGER(o,    1,UMMESSAGE_CODETAG_COMPRESS                  ,"compress"                        ,_pduCompress              ,pduCompress              ,"compress"                    ,"optional")
INTEGER(o,    1,UMMESSAGE_CODETAG_DCS                       ,"dcs"                             ,_pduDcs                   ,pduDcs                   ,"dcs"                         ,"optional")
INTEGER(o,    1,UMMESSAGE_CODETAG_MWI_PDU                   ,"mwi"                             ,_pduMwi                   ,pduMwi                   ,"mwi"                         ,"optional")
DATA(o   ,    0,UMMESSAGE_CODETAG_UDH                       ,"udh"                             ,_pduUdh                   ,pduUdh                   ,"udh"                         ,"optional")
DATA(o   ,    0,UMMESSAGE_CODETAG_CONTENT                   ,"content"                         ,_pduContent               ,pduContent               ,"content"                     ,"optional")
TEXT(o   ,    0,UMMESSAGE_CODETAG_PLAINTEXTCONTENT          ,"plaintext-content"               ,_plaintextContent         ,plaintextContent         ,"plaintext_content"           ,"optional")
INTEGER(o,    1,UMMESSAGE_CODETAG_ESMCLASS                  ,"esm-class"                       ,_esmClass                 ,esmClass                 ,"esm_class"                   ,"optional")
INTEGER(o,    1,UMMESSAGE_CODETAG_MESSAGECLASS              ,"message-class"                   ,_messageClass             ,messageClass             ,"message_class"               ,"optional")
STRING(o,    18,UMMESSAGE_CODETAG_CODING                    ,"coding"                          ,_pduCoding                ,pduCoding                ,"coding"                      ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_OPC                       ,"opc-srism"                       ,_opc_srism                ,opc_srism                ,"opc_srism"                   ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_DPC                       ,"dpc-srism"                       ,_dpc_srism                ,dpc_srism                ,"dpc_srism"                   ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_OPC2                      ,"opc-fsm"                         ,_opc_fsm                  ,opc_fsm                  ,"opc_fsm"                     ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_DPC2                      ,"dpc-fsm"                         ,_dpc_fsm                  ,dpc_fsm                  ,"dpc_fsm"                     ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_TCAPTYPE                  ,"tcap-type"                       ,_tcapType                 ,tcapType                 ,"tcap_type"                   ,"optional")
TEXT(o,       0,UMMESSAGE_CODETAG_EXTENSIONDATA             ,"extension-data"                  ,_extensionData            ,extensionData            ,"extension_data"              ,"optional")
INTEGER(o,    1,UMMESSAGE_CODETAG_PURGEFLAG                 ,"purge-flag"                      ,_purgeFlag                ,purgeFlag                ,"purge_flag"                  ,"indexed,optional")
STRING(o ,   18,UMMESSAGE_CODETAG_ALERTINGADDRESS           ,"alerting-address"                ,_alertingAddress          ,alertingAddress          ,"alerting_address"            ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_FROMCOUNTRY               ,"from-country"                    ,_fromCountry              ,fromCountry              ,"from_country"                ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_FROMOPERATORCODE          ,"from-operator-code"              ,_fromOperatorCode         ,fromOperatorCode         ,"from_cperator_code"          ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_FROMOPERATORNAME          ,"from-operator-name"              ,_fromOperatorName         ,fromOperatorName         ,"from_operator_name"          ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_ROUTEID                   ,"route-id"                        ,_routeId                  ,routeId                  ,"route_id"                    ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_SUBROUTEID                ,"subroute-id"                     ,_subrouteId               ,subrouteId               ,"subroute_id"                 ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_ROUTEDONPREFIX            ,"routed-on-prefix"                ,_routedOnPrefix           ,routedOnPrefix           ,"routed_on_prefix"            ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_AUTOROUTED                ,"auto-routed"                     ,_autoRouted               ,autoRouted               ,"auto_routed"                 ,"optional")
INTEGER(o,    2,UMMESSAGE_CODETAG_USERFLAGS                 ,"user-flags"                      ,_userFlags                ,userFlags                ,"user_flags"                  ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_INTERWORKINGTAPCODE       ,"interworking-tap-code"           ,_interworkingTapCode      ,interworkingTapCode      ,"interworking_tap_code"       ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_COSTTABLE                 ,"cost-table"                      ,_costTable                ,costTable                ,"cost_table"                  ,"optional")
DOUBLE(o ,    0,UMMESSAGE_CODETAG_MSUCOSTTX                 ,"msu-cost-tx"                     ,_msuCostTx                ,msuCostTx                ,"msu_cost_tx"                 ,"optional")
DOUBLE(o ,    0,UMMESSAGE_CODETAG_MSUCOSTRX                 ,"msu-cost-rx"                     ,_msuCostRx                ,msuCostRx                ,"msu_cost_rx"                 ,"optional")
DOUBLE(o ,    0,UMMESSAGE_CODETAG_SMSCOST                   ,"sms-cost"                        ,_smsCost                  ,smsCost                  ,"sms_cost"                    ,"optional")
DOUBLE(o ,    0,UMMESSAGE_CODETAG_INTERWORKINGCOST          ,"interworking-cost"               ,_interworkingCost         ,interworkingCost         ,"interworking_cost"           ,"optional")
DOUBLE(o ,    0,UMMESSAGE_CODETAG_TOTALCOST                 ,"total-cost"                      ,_totalCost                ,totalCost                ,"total_coost"                 ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_CHARGETABLE1              ,"charge-table1"                   ,_chargeTable1             ,chargeTable1             ,"charge_table1"               ,"optional")
DOUBLE(o ,    0,UMMESSAGE_CODETAG_CHARGEPRICE1              ,"charge-price1"                   ,_chargePrice1             ,chargePrice1             ,"charge_price1"               ,"optional")
DOUBLE(o ,    0,UMMESSAGE_CODETAG_PROFIT1                   ,"profit1"                         ,_profit1                  ,profit1                  ,"profit1"                     ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_CHARGETABLE2              ,"cahrge-table2"                   ,_chargeTable2             ,chargeTable2             ,"charge_table2"               ,"optional")
DOUBLE(o ,    0,UMMESSAGE_CODETAG_CHARGEPRICE2              ,"cahrge-price2"                   ,_chargePrice2             ,chargePrice2             ,"charge_price2"               ,"optional")
DOUBLE(o ,    0,UMMESSAGE_CODETAG_PROFIT2                   ,"profit2"                         ,_profit2                  ,profit2                  ,"profit2"                     ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_DESTINATIONQUOTATABLE     ,"destination-quota-table"         ,_destinationQuotaTable    ,destinationQuotaTable    ,"destination_quota_table"     ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_RETRYPATTERNTABLE         ,"retry-pattern-table"             ,_retryPatternTable        ,retryPatternTable        ,"retry_pattern"               ,"optional")
INTEGER(o,    1,UMMESSAGE_CODETAG_TT_SRI                    ,"tt-sri"                          ,_tt_sri                   ,tt_sri                   ,"tt_sri"                      ,"optional")
INTEGER(o,    1,UMMESSAGE_CODETAG_TT_FSM                    ,"tt-fsm"                          ,_tt_fsm                   ,tt_fsm                   ,"tt_fsm"                      ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_DLR_TEXT                  ,"dlr-text"                        ,_dlr_text                 ,dlr_text                 ,"dlr_text"                    ,"optional")
TEXT(o ,      0,UMMESSAGE_CODETAG_COMMENT_TEXT              ,"comment"                         ,_comment                  ,comment                  ,"comment"                     ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_HLR_OVERRIDE              ,"hlr-override"                    ,_hlr_override             ,hlr_override             ,"hlr_override"                ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_VAS_ESME                  ,"vas-esme"                        ,_vas_esme                 ,vas_esme                 ,"vas_esme"                    ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_VAS_IP                    ,"vas-ip"                          ,_vas_ip                   ,vas_ip                   ,"vas_ip"                      ,"optional")
DATE(o   ,   14,UMMESSAGE_CODETAG_DEFERRED                  ,"deferred"                        ,_deferred                 ,deferred                 ,"deferred"                    ,"optional")
INTEGER(o,    1,UMMESSAGE_CODETAG_EXPORTED                  ,"exported"                        ,_exported                 ,exported                 ,"exported"                    ,"optional")
TEXT(o ,      0,UMMESSAGE_CODETAG_OPTIONS                   ,"options"                         ,_options                  ,options                  ,"options"                     ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_INBOUND_METHOD            ,"inbound-method"                  ,_inboundMethod            ,inboundMethod            ,"inbound_method"              ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_INBOUND_TYPE              ,"inbound-type"                    ,_inboundType              ,inboundType              ,"inbound_type"                ,"optional")
DATA(o   ,    0,UMMESSAGE_CODETAG_USER_MESSAGE_REFERENCE    ,"user-message-reference"          ,_userMessageReference     ,userMessageReference     ,"user_message_reference"      ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_USER_REFERENCE            ,"user-reference"                  ,_userReference            ,userReference            ,"user_reference"              ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_PROVIDER_REFERENCE        ,"provider-reference"              ,_providerReference        ,providerReference        ,"provider_reference"          ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_ROUTER_REFERENCE          ,"router-reference"                ,_routerReference          ,routerReference          ,"router_reference"            ,"optional")
DATE(o   ,   14,UMMESSAGE_CODETAG_SUBMIT_TIMESTAMP          ,"submit-timestamp"                ,_submitTimestamp          ,submitTimestamp          ,"submit_ts"                   ,"optional")
DATE(o   ,   14,UMMESSAGE_CODETAG_SUBMIT_ACK_TIMESTAMP      ,"submit-ack-timestamp"            ,_submitAckTimestamp       ,submitAckTimestamp       ,"submit_ack_ts"               ,"optional")
DATE(o   ,   14,UMMESSAGE_CODETAG_SUBMIT_ERROR_TIMESTAMP    ,"submit-err-timestamp"            ,_submitErrorTimestamp     ,submitErrorTimestamp     ,"submit_error_ts"             ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_SUBMIT_STRING             ,"submit-string"                   ,_submitString             ,submitString             ,"submit_string"               ,"optional")
INTEGER(o,    1,UMMESSAGE_CODETAG_SUBMIT_ERROR_CODE         ,"submit-error-code"               ,_submitErrorCode          ,submitErrorCode          ,"submit_error_code"           ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_METHOD                    ,"method"                          ,_method                   ,method                   ,"method"                      ,"optional")
INTEGER(o,    1,UMMESSAGE_CODETAG_NETWORK_ERROR_CODE        ,"network-error-code"              ,_networkErrorCode         ,networkErrorCode         ,"network_error_code"          ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_DELIVERYREPORTNUMBER      ,"delivery-report-number"          ,_deliveryReportNumber     ,deliveryReportNumber     ,"delivery_report_number"      ,"optional")
INTEGER(o ,   1,UMMESSAGE_CODETAG_REPLACE_IF_PRESENT        ,"replace-if-present"              ,_replaceIfPresentFlag     ,replaceIfPresentFlag     ,"replace_if_present"          ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_TYPE                      ,"type"                            ,_type                     ,type                     ,"type"                        ,"optional")
STRING(o ,   18,UMMESSAGE_CODETAG_LINKED_MESSAGE_ID         ,"linked-message-id"               ,_linkedMessageId          ,linkedMessageId          ,"linked_message_id"           ,"indexed,optional")
INTEGER(o,    1,UMMESSAGE_CODETAG_MULTIPART_REF             ,"multipart-ref"                   ,_multipartRef             ,multipartRef             ,"multipart_ref"               ,"optional")
INTEGER(o,    1,UMMESSAGE_CODETAG_CURRENT_PART              ,"current-part"                    ,_currentPart              ,currentPart              ,"current_part"                ,"optional")
INTEGER(o,    1,UMMESSAGE_CODETAG_MAX_PARTS                 ,"max-parts"                       ,_maxParts                 ,maxParts                 ,"max_parts"                   ,"optional")
TEXT(o ,      0,UMMESSAGE_CODETAG_INBOUND_MESSAGE_IDS       ,"inbound-message-ids"             ,_inboundMessageIds        ,inboundMessageIds        ,"inbound_message_ids"         ,"optional")
TEXT(o ,      0,UMMESSAGE_CODETAG_OUTBOUND_MESSAGE_IDS      ,"outbound-message-ids"            ,_outboundMessageIds      ,outboundMessageIds        ,"outbound_message_ids"        ,"optional")

